<?php
/**
 * Default config header
 *
 * To replace this add a file tao/conf/header/client_lib_registry.conf.php
 */

return array(
    'tao' => 'http://localhost/TAO/tao/views/js',
    'taoCss' => 'http://localhost/TAO/tao/views/css',
    'funcAcl' => 'http://localhost/TAO/funcAcl/views/js',
    'funcAclCss' => 'http://localhost/TAO/funcAcl/views/css',
    'taoItems' => 'http://localhost/TAO/taoItems/views/js',
    'taoItemsCss' => 'http://localhost/TAO/taoItems/views/css',
    'IMSGlobal/jquery_2_1_1' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/IMSGlobal/jquery_2_1_1',
    'OAT/lodash' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/lodash',
    'OAT/async' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/async',
    'OAT/raphael' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/raphael',
    'OAT/scale.raphael' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/scale.raphael',
    'OAT/util/xml' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/util/xml',
    'OAT/util/math' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/util/math',
    'OAT/util/html' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/util/html',
    'OAT/util/EventMgr' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/util/EventMgr',
    'OAT/util/event' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/util/event',
    'OAT/sts/common' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/sts/common',
    'OAT/interact' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/interact',
    'OAT/interact-rotate' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/interact-rotate',
    'OAT/sts/transform-helper' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/sts/transform-helper',
    'OAT/handlebars' => 'http://localhost/TAO/taoQtiItem/views/js/portableSharedLibraries/OAT/handlebars',
    'taoQtiItem' => 'http://localhost/TAO/taoQtiItem/views/js',
    'taoQtiItemCss' => 'http://localhost/TAO/taoQtiItem/views/css',
    'qtiItemPci' => 'http://localhost/TAO/qtiItemPci/views/js',
    'qtiItemPciCss' => 'http://localhost/TAO/qtiItemPci/views/css',
    'taoOpenWebItem' => 'http://localhost/TAO/taoOpenWebItem/views/js',
    'taoOpenWebItemCss' => 'http://localhost/TAO/taoOpenWebItem/views/css',
    'taoTests' => 'http://localhost/TAO/taoTests/views/js',
    'taoTestsCss' => 'http://localhost/TAO/taoTests/views/css',
    'taoQtiTest' => 'http://localhost/TAO/taoQtiTest/views/js',
    'taoQtiTestCss' => 'http://localhost/TAO/taoQtiTest/views/css',
    'taoTestTaker' => 'http://localhost/TAO/taoTestTaker/views/js',
    'taoTestTakerCss' => 'http://localhost/TAO/taoTestTaker/views/css',
    'taoGroups' => 'http://localhost/TAO/taoGroups/views/js',
    'taoGroupsCss' => 'http://localhost/TAO/taoGroups/views/css',
    'taoResultServer' => 'http://localhost/TAO//taoResultServer/views/js',
    'taoResultServerCss' => 'http://localhost/TAO//taoResultServer/views/css',
    'taoDelivery' => 'http://localhost/TAO/taoDelivery/views/js',
    'taoDeliveryCss' => 'http://localhost/TAO/taoDelivery/views/css',
    'taoOutcomeRds' => 'http://localhost/TAO/taoOutcomeRds/views/js',
    'taoOutcomeRdsCss' => 'http://localhost/TAO/taoOutcomeRds/views/css',
    'taoOutcomeUi' => 'http://localhost/TAO/taoOutcomeUi/views/js',
    'taoOutcomeUiCss' => 'http://localhost/TAO/taoOutcomeUi/views/css',
    'taoCe' => 'http://localhost/TAO/taoCe/views/js',
    'taoCeCss' => 'http://localhost/TAO/taoCe/views/css',
    'taoDevTools' => 'http://localhost/TAO/taoDevTools/views/js',
    'taoDevToolsCss' => 'http://localhost/TAO/taoDevTools/views/css',
);
